version: "3.8"

services:
  django:
    build: .
    volumes:
      - .:/usr/src/celery-tut
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - pgdb
      - redis

  celery:
    build: .
    command: celery -A celery_tut worker -l INFO
    volumes:
      - .:/usr/src/celery-tut
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    command: celery -A celery_tut beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - django
      - redis
      - celery

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

volumes:
  pgdata:
